{{- if and .Values.license.enabled .Values.license.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.name" . }}-license
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.license.onePassword.vault }}/items/{{ .Values.license.onePassword.item }}"
{{- end }}