{{- if .Values.magnoliaPublic.ingress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "mgnl.public.name" . }}
  labels:
    {{- $mergedLabels := include "mgnl.public.ingress.labels" . | fromYaml }}
    {{- if $mergedLabels }}
      {{- toYaml $mergedLabels | nindent 4 }}
    {{- end }}
    {{- include "mgnl.labels" . | nindent 4 }}
  {{- $mergedAnnotations := include "mgnl.public.ingress.annotations" . | fromYaml }}
  {{- if $mergedAnnotations }}
  annotations:
    {{- toYaml $mergedAnnotations | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.magnoliaPublic.ingress.hostname }}
      secretName: {{ include "mgnl.public.name" . }}-tls
  rules:
    - host: {{ .Values.magnoliaPublic.ingress.hostname }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "mgnl.public.name" . }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ include "mgnl.public.name" . }}
              servicePort: http
              {{- end }}
{{- end }}