{{- if .Values.magnoliaAuthor.datasource.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.author.name" . }}-datasource-password
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.magnoliaAuthor.datasource.onePassword.vault }}/items/{{ .Values.magnoliaAuthor.datasource.onePassword.item }}"
{{- end }}
