{{- if .Values.magnoliaPublic.assetIngress.enabled -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "mgnl.public.name" . }}-assets
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
  {{- $mergedAnnotations := include "mgnl.public.assetIngress.annotations" . | fromYaml }}
  {{- if $mergedAnnotations }}
  annotations:
    {{- toYaml $mergedAnnotations | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.magnoliaPublic.assetIngress.hostname }}
      secretName: {{ include "mgnl.public.name" . }}-assets-tls
  rules:
    - host: {{ .Values.magnoliaPublic.assetIngress.hostname }}
      http:
        paths:
          - path: /(.*)
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "mgnl.public.name" . }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ include "mgnl.public.name" . }}
              servicePort: http
              {{- end }}
{{- end }}