{{- if .Values.magnoliaLightModuleUpdater.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.name" . }}-light-module-updater
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.magnoliaLightModuleUpdater.onePassword.vault }}/items/{{ .Values.magnoliaLightModuleUpdater.onePassword.item }}"
{{- end }}
