{{- if .Values.magnoliaActivation.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.name" . }}-activation-keypair
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.magnoliaActivation.onePassword.vault }}/items/{{ .Values.magnoliaActivation.onePassword.item }}"
{{- end }}
