{{- if .Values.magnolia.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.name" . }}-custom-env-secrets
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.magnolia.onePassword.vault }}/items/{{ .Values.magnolia.onePassword.item }}"
{{- end }}
