{{- if and .Values.license.enabled (not .Values.license.onePassword.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgnl.name" . }}-license
  labels:
{{ include "mgnl.labels" . | indent 4 }}
data:
  license.key: {{ .Values.license.key | b64enc }}
  email: {{ .Values.license.email | b64enc }}
{{- end }}