{{- if and .Values.mysql.enabled .Values.mysql.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "mgnl.mysql.name" . }}-passwords
  labels:
{{ include "mgnl.labels" . | indent 4 }}
spec:
  itemPath: "vaults/{{ .Values.mysql.onePassword.vault }}/items/{{ .Values.mysql.onePassword.item }}"
{{- end }}
