apiVersion: v2
name: mgnl
description: Run Magnolia CMS on Kubernetes in production
type: application
version: 1.3.4
appVersion: "1.3.4"
home: https://github.com/neoskop/mgnl-on-k8s
sources:
  - https://github.com/neoskop/mgnl-on-k8s
maintainers:
  - name: Arne Diekmann
    email: diekmann@neoskop.de
    url: https://www.neoskop.de
